### ISSUE TITLE
NullPointerException, "Could not pass event CreatureSpawnEvent to DistributedMobSpawns v2.2.1"

### ISSUE THREAD

**Issue by robertoccu** [kickash32/DistributedMobSpawns#6]
When I put the plugin (v2.2.1) on my server and someone enters, the console is flooded by NullPointerExceptions and the message "Could not pass event CreatureSpawnEvent to DistributedMobSpawns v2.2.1" with the stack trace.

/dms toggle works but /dms stats return null too.

This is the complete log of the server: https://pastebin.com/4Bw8LGg0

**Comment by kickash32** [comment]
You did something weird, did you reload?

**Comment by robertoccu** [comment]
I only put the plugin in plugins folder and start the server. At the next restart I remove it because of the errors.

**Comment by Metamaniac** [comment]
Having a very similar issue on my own 1.13.2 server, doing /mvtp into a new world caused the console to be flooded with a similar message for roughly 7 minutes straight, sending about 6 per second. This could be in part due to the nature of the world being generated on an older minecraft version and optimized for 1.13, as I hadn't seen many error messages in my normal world (though they had happened before). Although I do still get NullPointerExceptions upon enabling and disabling the plugin- which has always happened regardless of version.

**Comment by kickash32** [comment]
I highly suspect multiverse has something to do with this, can you remove multiverse and see if you get the same errors?

**Comment by kickash32** [comment]
Ok I have tracked down the issue to interaction with multiverse. This will be fixed in the next build soon.
